language: java

jdk:
  - oraclejdk8

before_install:
  - apt-get update -qq
  - apt-get install -y openssl apr

install: true

script: mvn clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)
