language: java

sudo: required

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libapr1
  - wget http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2d-0ubuntu1_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/openssl_1.0.2d-0ubuntu1_amd64.deb
  - sudo dpkg -i libssl1.0.0_1.0.2d-0ubuntu1_amd64.deb
  - sudo dpkg -i openssl_1.0.2d-0ubuntu1_amd64.deb

install: true

script: mvn clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)
