language: java

sudo: required

jdk:
  - oraclejdk8

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl apr

install: true

script: mvn clean test

after_success:
  - bash <(curl -s https://codecov.io/bash)
